name: pucpr-DevOps-AS2

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            edsonlmachado/pucpr-devops-as2-img:v1

  test:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install dependencies
      run: pip install Flask
    - name: Run SAST Scan
      uses: appthreat/sast-scan-action@main  # Assuming 'main' is the default branch
      with:
        type: python
